---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: klajoie-test-pvc
  labels:
    username: klajoie
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
