---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klajoie-test-app-deployment
  labels:
    app: klajoie-test-app
    username: klajoie
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klajoie-test-app
      username: klajoie
      env: test
  template:
    metadata:
      labels:
        app: klajoie-test-app
        username: klajoie
        env: test
    spec:
      containers:
        - name: test-redis
          image: redis:7
          volumeMounts:
          - name: klajoie-test-pvc
            mountPath: "/data"
      volumes:
      - name: klajoie-test-pvc
        persistentVolumeClaim:
          claimName: klajoie-test-pvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: klajoie-test-app
      username: klajoie
      env: test
  template:
    metadata:
      labels:
        app: klajoie-test-app
        username: klajoie
        env: test
    spec:
      containers:
        - name: klajoie-test-flask
          imagePullPolicy: Always
          image: lajoiekatelyn/gene_flask_app:1.0
          env:
          - name: FLASK_APP
            value: "gene_api.py"
          ports:
          - name: http
            containerPort: 5000
