---
apiVersion: v1
kind: Service
metadata:
  name: klajoie-test-flask-service
spec:
  type: ClusterIP
  selector:
    app: klajoie-test-app
    username: klajoie
    env: test
  ports:
  - name: klajoie-test-flask
    port: 5000
    targetPort: 5000
