---
apiVersion: v1
kind: Service
metadata:
  name: klajoie-test-redis-service
  labels:
    username: klajoie
    env: test
spec:
  type: ClusterIP
  selector:
    app: klajoie-test-app
    username: klajoie
    env: test
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
